version: "3.5"
services:
  core:
    container_name: compute-core
    image: compute-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISABLE_AUTHENTICATION: ${DISABLE_AUTHENTICATION}
      API_ROOT_PATH:
      API_SCHEME: http
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      API_IAM_CLIENT_ID: some-uuid
      API_IAM_CLIENT_SECRET:
      API_IAM_CLIENT_SCOPES: openid profile
      API_IAM_CLIENT_AUDIENCE: compute-api
      PERMISSIONS_API_URL: https://permissions.srcdev.skao.int/api/v1
      PERMISSIONS_SERVICE_NAME: compute-api
      PERMISSIONS_SERVICE_VERSION: 1
    ports:
      - 8080:8080
