#!/bin/bash

cd src/fastapi_app/rest

printf "TEST_ENV=${TEST_ENV}
CLIENT_CONF_URL=${CLIENT_CONF_URL}
CLIENT_NAME=${CLIENT_NAME}
CLIENT_SCOPES=${CLIENT_SCOPES}
PERMISSIONS_ROOT_GROUP=${PERMISSIONS_ROOT_GROUP}
PERMISSIONS_RELPATH=${PERMISSIONS_RELPATH}
PERMISSIONS_NAME=${PERMISSIONS_NAME}
ROLES_RELPATH=${ROLES_RELPATH}
ROLES_NAME=${ROLES_NAME}
SESSION_MIDDLEWARE_SECRET_KEY=${SESSION_MIDDLEWARE_SECRET_KEY}
SKA_CLIENT_ID=${SKA_CLIENT_ID}
SKA_CLIENT_SECRET=${SKA_CLIENT_SECRET}" > .env


uvicorn server:app --host "0.0.0.0" --port 4747 --reload --reload-dir ../common/ --reload-dir ../api/ --reload-dir ../../../etc/ --reload-include *.json
